-- 232_voucher_record_management.sql
-- Accounting Phase 1 — voucher record management for the manual vouchers
-- (gl_receipt / gl_payment / gl_contra / gl_journal). Adds: load a voucher,
-- find by document number, previous/next navigation, in-place edit, and
-- void/delete. All guarded so only UNLOCKED manual vouchers can be changed:
--   * status must be 'posted'
--   * source must be one of the four manual voucher types (never a module- or
--     settlement-generated entry)
--   * the posting period must be open (not closed_through)
--   * the entry must not be referenced by any settlement allocation
-- The ledger already ignores status='void', so voiding removes the entry from
-- all books while keeping the audit trail.

-- The four editable manual voucher sources.
create or replace function acct_is_manual_voucher(p_source text)
 returns boolean language sql immutable as
$$ select p_source in ('gl_receipt','gl_payment','gl_contra','gl_journal') $$;

-- Guard: raise if the entry cannot be edited/voided; returns the entry row.
create or replace function acct_voucher_guard(p_entry uuid)
 returns journal_entries language plpgsql security definer set search_path to 'public'
as $function$
declare e journal_entries%rowtype; v_closed date;
begin
  if not is_staff() then raise exception 'Not authorized'; end if;
  select * into e from journal_entries where id = p_entry and company_id = auth_company_id();
  if not found then raise exception 'Voucher not found'; end if;
  if e.status <> 'posted' then raise exception 'Only a posted voucher can be changed (this one is %).', e.status; end if;
  if not acct_is_manual_voucher(e.source) then
    raise exception 'This voucher was generated by another module and cannot be edited here.';
  end if;
  select closed_through into v_closed from acct_settings where company_id = e.company_id;
  if v_closed is not null and e.entry_date <= v_closed then
    raise exception 'The period is closed through % — this voucher cannot be changed.', v_closed;
  end if;
  if exists (select 1 from allocations where settle_entry_id = e.id) then
    raise exception 'This voucher has bill allocations against it — remove them first.';
  end if;
  return e;
end $function$;

-- Load one voucher (header + raw lines) for the editor.
create or replace function gl_voucher_get(p_entry uuid)
 returns jsonb language plpgsql stable security definer set search_path to 'public'
as $function$
declare e journal_entries%rowtype; v jsonb;
begin
  if not is_staff() then raise exception 'Not authorized'; end if;
  select * into e from journal_entries where id = p_entry and company_id = auth_company_id();
  if not found then return null; end if;
  select jsonb_build_object(
    'id', e.id, 'entry_no', e.entry_no, 'entry_date', e.entry_date, 'memo', e.memo,
    'reference', e.reference, 'source', e.source, 'status', e.status,
    'editable', (e.status = 'posted' and acct_is_manual_voucher(e.source)
                 and not exists (select 1 from allocations where settle_entry_id = e.id)),
    'lines', coalesce((select jsonb_agg(jsonb_build_object(
        'account_id', l.account_id, 'description', l.description,
        'debit', l.debit, 'credit', l.credit, 'cost_center', l.cost_center, 'tag_area', l.tag_area
      ) order by l.created_at) from journal_lines l where l.entry_id = e.id), '[]'::jsonb)
  ) into v;
  return v;
end $function$;

-- Find a voucher id by its document number (optionally within one source), for
-- the "go to document" box.
create or replace function gl_voucher_find(p_entry_no text, p_source text default null)
 returns uuid language sql stable security definer set search_path to 'public'
as $function$
  select id from journal_entries
  where company_id = auth_company_id() and entry_no = btrim(p_entry_no)
    and (p_source is null or source = p_source)
  order by created_at desc limit 1;
$function$;

-- Previous / next voucher of the same source (by entry_no). p_dir: 'prev' | 'next'.
-- When p_entry is null, returns the latest (for next) / earliest (for prev).
create or replace function gl_voucher_nav(p_source text, p_entry uuid, p_dir text)
 returns uuid language plpgsql stable security definer set search_path to 'public'
as $function$
declare v_no text; v_id uuid; v_co uuid := auth_company_id();
begin
  if p_entry is not null then select entry_no into v_no from journal_entries where id = p_entry and company_id = v_co; end if;
  if p_dir = 'prev' then
    select id into v_id from journal_entries
      where company_id = v_co and source = p_source and status <> 'void'
        and (v_no is null or entry_no < v_no)
      order by entry_no desc limit 1;
  else
    select id into v_id from journal_entries
      where company_id = v_co and source = p_source and status <> 'void'
        and (v_no is null or entry_no > v_no)
      order by entry_no asc limit 1;
  end if;
  return v_id;
end $function$;

-- In-place edit of an unlocked manual voucher: replace its lines and header
-- fields, keeping the same document number. p_lines = journal-style
-- [{account_id, debit, credit, description, cost_center, tag_area}].
create or replace function gl_voucher_update(p_entry uuid, p_date date, p_memo text, p_reference text, p_lines jsonb)
 returns jsonb language plpgsql security definer set search_path to 'public'
as $function$
declare e journal_entries%rowtype; ln jsonb; d numeric(18,2); c numeric(18,2); v_closed date;
begin
  e := acct_voucher_guard(p_entry);
  -- New date must also be in an open period.
  select closed_through into v_closed from acct_settings where company_id = e.company_id;
  if v_closed is not null and p_date <= v_closed then
    raise exception 'Period is closed through % — cannot move the voucher to %.', v_closed, p_date;
  end if;
  perform gl_validate(e.company_id, p_lines);   -- balanced + valid accounts
  update journal_entries set entry_date = p_date, memo = p_memo, reference = p_reference where id = p_entry;
  delete from journal_lines where entry_id = p_entry;
  for ln in select * from jsonb_array_elements(p_lines) loop
    d := round(coalesce((ln->>'debit')::numeric, 0), 2);
    c := round(coalesce((ln->>'credit')::numeric, 0), 2);
    if d = 0 and c = 0 then continue; end if;
    insert into journal_lines(entry_id, account_id, description, debit, credit, cost_center, tag_area)
    values (p_entry, (ln->>'account_id')::uuid, ln->>'description', d, c, ln->>'cost_center', ln->>'tag_area');
  end loop;
  perform acct_log(e.company_id, 'edited', e.source, e.entry_no, jsonb_build_object('entry_id', p_entry));
  return jsonb_build_object('entry_id', p_entry, 'entry_no', e.entry_no);
end $function$;

-- Void (delete) an unlocked manual voucher — removed from all books, audit kept.
create or replace function gl_voucher_void(p_entry uuid, p_reason text default null)
 returns jsonb language plpgsql security definer set search_path to 'public'
as $function$
declare e journal_entries%rowtype;
begin
  e := acct_voucher_guard(p_entry);
  update journal_entries set status = 'void',
    memo = coalesce(memo,'') || case when p_reason is not null and btrim(p_reason) <> '' then ' [VOID: ' || p_reason || ']' else ' [VOID]' end
  where id = p_entry;
  perform acct_log(e.company_id, 'voided', e.source, e.entry_no, jsonb_build_object('entry_id', p_entry, 'reason', p_reason));
  return jsonb_build_object('entry_id', p_entry, 'entry_no', e.entry_no, 'voided', true);
end $function$;

grant execute on function gl_voucher_get(uuid) to authenticated;
grant execute on function gl_voucher_find(text, text) to authenticated;
grant execute on function gl_voucher_nav(text, uuid, text) to authenticated;
grant execute on function gl_voucher_update(uuid, date, text, text, jsonb) to authenticated;
grant execute on function gl_voucher_void(uuid, text) to authenticated;
