-- 284 Fixes found auditing the access-control flow.
--
-- 1. staff_users_list handed every staff user the whole company's permission
--    maps. Five screens call it — the hotels booking screens want names for a
--    "handled by" picker — so it stays open, but the permissions column now
--    only reaches a caller who may administer users.
--
-- 2. The Restrict tab read the four master trees as the signed-in user, so a
--    delegated user manager who is himself restricted saw only his own corner
--    of them — and saving wrote back only what he could see, silently dropping
--    the restrictions he never saw. Administering someone else's access is a
--    privileged act (users.manage_roles), so it reads the full trees.

create or replace function public.staff_users_list(p_id uuid default null)
returns table(id uuid, full_name text, is_active boolean, company_id uuid,
              created_at timestamp with time zone, username text, email text,
              phone text, department text, designation text, permissions jsonb)
language sql security definer set search_path to 'public' as $$
  select p.id,
         p.full_name,
         p.is_active,
         p.company_id,
         p.created_at,
         replace(u.email::text, '@vista.local'::text, ''::text) as username,
         p.email,
         p.phone,
         p.department,
         p.designation,
         -- Only a user administrator sees who is allowed what.
         case when staff_perm_strict('users.view') then p.permissions else '{}'::jsonb end
  from public.profiles p
  join auth.users u on u.id = p.id
  where is_staff()
    and p.company_id = auth_company_id()
    and (p_id is null or p.id = p_id)
  order by p.created_at;
$$;

-- The four trees the Restrict tab picks from, whole, for a caller entitled to
-- set somebody else's restrictions. Deliberately not filtered by the caller's
-- own staff_scopes: they are editing another user's list, not browsing their
-- own data, and a partial list would be saved back as a complete one.
create or replace function public.staff_scope_masters()
returns jsonb language sql stable security definer set search_path to 'public' as $$
  select case when not staff_perm_strict('users.manage_roles') then null else jsonb_build_object(
    'account', coalesce((select jsonb_agg(jsonb_build_object('id', a.id, 'name', a.name, 'code', a.code,
                                  'parent_id', a.parent_id, 'is_group', a.is_group) order by a.code)
                         from accounts a where a.company_id = auth_company_id()), '[]'::jsonb),
    'product', coalesce((select jsonb_agg(jsonb_build_object('id', x.id, 'name', x.name,
                                  'parent_id', x.parent_id, 'is_group', x.is_group) order by x.name)
                         from acct_products x where x.company_id = auth_company_id()), '[]'::jsonb),
    'cost_center', coalesce((select jsonb_agg(jsonb_build_object('id', c.id, 'name', c.name, 'code', c.code,
                                  'parent_id', c.parent_id, 'is_group', c.is_group) order by c.name)
                         from acct_cost_centers c where c.company_id = auth_company_id()), '[]'::jsonb),
    'tag_area', coalesce((select jsonb_agg(jsonb_build_object('id', t.id, 'name', t.name,
                                  'parent_id', t.parent_id, 'is_group', t.is_group) order by t.name)
                         from acct_tag_areas t where t.company_id = auth_company_id()), '[]'::jsonb)
  ) end;
$$;
revoke all on function public.staff_scope_masters() from anon;

-- 3. Petty Cash vouchers could not be edited or voided at all: they post with
--    source 'gl_petty', which acct_is_manual_voucher never listed, so
--    acct_voucher_guard turned every attempt away as "generated by another
--    module". The Petty Cash screen offers Save changes and Delete like the
--    other three, and both failed. (Pre-existing; found auditing the flow.)
create or replace function public.acct_is_manual_voucher(p_source text)
returns boolean language sql immutable as
$$ select p_source in ('gl_receipt', 'gl_payment', 'gl_contra', 'gl_petty', 'gl_journal') $$;

-- 4. staff_require_journal_right looked an entry up by id alone. Its caller
--    checks the company first, but the function should not depend on that.
create or replace function public.staff_require_journal_right(p_entry uuid, p_right text)
returns void language plpgsql stable security definer set search_path to 'public' as $$
declare v_doc text; v_by uuid; v_auth boolean;
begin
  select staff_doc_key(e.source), e.created_by,
         exists (select 1 from pending_vouchers pv where pv.posted_entry_id = e.id)
    into v_doc, v_by, v_auth
  from journal_entries e where e.id = p_entry and e.company_id = auth_company_id();
  if v_doc is null then return; end if;

  perform staff_require_doc(v_doc, p_right);
  if v_by is not null and v_by <> auth.uid() and not staff_doc_right(v_doc, 'edit_others') then
    raise exception 'This voucher was entered by another user and you may not change it.';
  end if;
  if v_auth and not staff_doc_right(v_doc, 'edit_authorized') then
    raise exception 'This voucher has been authorised and you may not change it.';
  end if;
end $$;
