-- ============================================================
-- 386 — A voided receipt gives its bill back, and every bill has a due date
--
-- Three things 385 left wrong, found on the first day of use.
--
-- 1. Deleting a voucher does not delete its row: gl_voucher_void marks it
--    'void' and keeps it for the audit trail. 385's release trigger fired
--    BEFORE DELETE only, so RCT-00001 was voided and CI-000005 stayed at
--    113,000 outstanding with the void receipt's allocation still on it. The
--    trigger fires on the update to 'void' as well now, through one routine,
--    and every entry already void is run through it. acct_voucher_guard used
--    to refuse deleting a receipt that carried allocations at all — under
--    385 that is exactly the case the release exists for, so the refusal is
--    kept for EDIT (an amount changing under an allocation) and lifted for
--    delete.
--
-- 2. No bill had a due date, because the backfill passed null and the car
--    postings had none to pass. Now: a trade voucher's bill carries the
--    voucher's due date; a car sale's bill is due on its first
--    instalment; a month of charges is due by the end of
--    that month; and anything else falls back to the bill date plus the
--    party's credit days, which is what credit days are for.
--
-- 3. (front end) the popup gets a Pick button per bill.
--
-- The ageing report reads these same bills, so once the void receipt is
-- released ABDUL JALAL ages at 123,500 (123,000 + 500) — the ledger balance —
-- rather than 113,500.
-- ============================================================
begin;

-- ── the release, as one routine ────────────────────────────────────────────
create or replace function public.journal_entry_release_open_items_for(p_entry uuid, p_entry_no text)
returns void
language plpgsql security definer
set search_path to 'public'
as $function$
declare v_settled text;
begin
  -- What this entry had settled is given back to the bills it settled.
  update open_items oi
     set outstanding_base = oi.outstanding_base + s.amt, status = 'open'
    from (select open_item_id, sum(amount_base) as amt from allocations where settle_entry_id = p_entry group by 1) s
   where s.open_item_id = oi.id;
  delete from allocations where settle_entry_id = p_entry;
  -- A bill something else has settled against cannot go.
  select string_agg(distinct e.entry_no, ', ') into v_settled
    from allocations a join open_items oi on oi.id = a.open_item_id join journal_entries e on e.id = a.settle_entry_id
   where oi.entry_id = p_entry;
  if v_settled is not null then
    raise exception '% has been adjusted against by % — reverse that first, then this can be changed.', p_entry_no, v_settled;
  end if;
  delete from open_items where entry_id = p_entry;
end $function$;
revoke all on function public.journal_entry_release_open_items_for(uuid, text) from public, anon, authenticated;

create or replace function public.journal_entry_release_open_items()
returns trigger
language plpgsql security definer
set search_path to 'public'
as $function$
begin
  if tg_op = 'UPDATE' then
    if new.status = 'void' and old.status is distinct from 'void' then
      perform journal_entry_release_open_items_for(old.id, old.entry_no);
    end if;
    return new;
  end if;
  perform journal_entry_release_open_items_for(old.id, old.entry_no);
  return old;
end $function$;
drop trigger if exists trg_journal_entry_release_open_items on public.journal_entries;
create trigger trg_journal_entry_release_open_items
  before delete or update of status on public.journal_entries
  for each row execute function public.journal_entry_release_open_items();

-- ── deleting an adjusted receipt is allowed; the release handles it ─────────
create or replace function public.acct_voucher_guard(p_entry uuid, p_right text default 'edit')
 returns journal_entries language plpgsql security definer set search_path to 'public'
as $function$
declare e journal_entries%rowtype; v_closed date;
begin
  if not is_staff() then raise exception 'Not authorized'; end if;
  select * into e from journal_entries where id = p_entry and company_id = auth_company_id();
  if not found then raise exception 'Voucher not found'; end if;
  perform staff_require_journal_right(p_entry, p_right);
  if e.status <> 'posted' then raise exception 'Only a posted voucher can be changed (this one is %).', e.status; end if;
  if not acct_is_manual_voucher(e.source) then
    raise exception 'This voucher was generated by another module and cannot be edited here.';
  end if;
  select closed_through into v_closed from acct_settings where company_id = e.company_id;
  if v_closed is not null and e.entry_date <= v_closed then
    raise exception 'The period is closed through % — this voucher cannot be changed.', v_closed;
  end if;
  -- An amount must not change under an allocation. A delete gives the
  -- allocations back through trg_journal_entry_release_open_items instead.
  if p_right <> 'delete' and exists (select 1 from allocations where settle_entry_id = e.id) then
    raise exception 'This voucher has bill allocations against it — remove them first.';
  end if;
  return e;
end $function$;

-- ── every bill has a due date ──────────────────────────────────────────────
create or replace function public.open_item_raise(
  p_company uuid, p_entry uuid, p_account uuid, p_direction text, p_doc_type text, p_doc_no text,
  p_doc_date date, p_due date, p_amount numeric)
returns uuid
language plpgsql security definer
set search_path to 'public'
as $function$
declare v_id uuid; v_party uuid; v_date date; v_due date; v_days int;
begin
  if p_account is null or round(coalesce(p_amount, 0), 2) <= 0 then return null; end if;
  select a.party_id, coalesce(nullif(p.credit_days, 0), a.credit_days, 0)
    into v_party, v_days
    from accounts a left join parties p on p.id = a.party_id where a.id = p_account;
  v_date := coalesce(p_doc_date, current_date);
  -- The voucher's own due date; else the bill date plus the party's credit days.
  v_due := coalesce(p_due, v_date + coalesce(v_days, 0));
  -- one bill per (entry, account): a re-run adds nothing
  select id into v_id from open_items where entry_id = p_entry and account_id = p_account and direction = p_direction;
  if v_id is not null then return v_id; end if;
  insert into open_items(company_id, account_id, party_id, direction, doc_type, doc_no, doc_date, due_date,
                         currency, amount_base, outstanding_base, entry_id, status)
  values (p_company, p_account, v_party, p_direction, p_doc_type, p_doc_no, v_date, v_due,
          'SAR', round(p_amount, 2), round(p_amount, 2), p_entry, 'open')
  returning id into v_id;
  return v_id;
end $function$;
revoke all on function public.open_item_raise(uuid, uuid, uuid, text, text, text, date, date, numeric) from public, anon, authenticated;

-- The car sale is due on its first instalment (the schedule, which can start
-- before the contract's start date — CI-000005's does); a month of charges
-- by the end of that month.
create or replace function public.car_post_entry(p_company uuid, p_date date, p_memo text, p_source text, p_reference text, p_lines jsonb)
returns boolean
language plpgsql
security definer
set search_path to 'public'
as $function$
declare v_entry uuid; v_no text; v_one boolean; l record; v_due date;
begin
  if exists (select 1 from journal_entries where company_id = p_company and source = p_source and reference = p_reference) then
    return false;
  end if;
  v_one := coalesce((select value = 'true' from erp_settings where key = 'ledger_uses_doc_no'), false);
  if p_source = 'car_scharge_month' then
    v_no := next_doc_number(p_company, 'car_scharge_month');
  elsif v_one and p_reference ~ '^[A-Z]{2,5}-[0-9]+$'
        and not exists (select 1 from journal_entries where company_id = p_company and entry_no = p_reference) then
    v_no := p_reference;
  else
    v_no := next_doc_number(p_company, 'journal');
  end if;
  insert into journal_entries(company_id, entry_no, entry_date, memo, status, source, reference, created_by)
  values (p_company, v_no, coalesce(p_date, current_date), p_memo, 'posted', p_source, p_reference, auth.uid())
  returning id into v_entry;
  insert into journal_lines(entry_id, account_id, description, debit, credit, cost_center, tag_area)
  select v_entry,
         coalesce(nullif(l->>'account_id','')::uuid, acct(p_company, l->>'code')),
         p_memo,
         round(coalesce((l->>'debit')::numeric, 0), 2), round(coalesce((l->>'credit')::numeric, 0), 2),
         nullif(btrim(coalesce(l->>'cost_center','')), ''),
         nullif(btrim(coalesce(l->>'tag_area','')), '')
  from jsonb_array_elements(p_lines) l
  where coalesce((l->>'debit')::numeric, 0) <> 0 or coalesce((l->>'credit')::numeric, 0) <> 0;
  -- A car sale and a month of charges are bills: one per customer debited.
  if p_source in ('car_sale', 'car_scharge_month') then
    if p_source = 'car_sale' then
      select coalesce((select min(i.due_date) from car_installments i where i.contract_id = c.id), c.start_date, c.contract_date)
        into v_due from car_contracts c where c.company_id = p_company and c.contract_no = p_reference;
    else
      v_due := (date_trunc('month', coalesce(p_date, current_date)) + interval '1 month - 1 day')::date;
    end if;
    for l in select jl.account_id, jl.debit from journal_lines jl join accounts a on a.id = jl.account_id
              where jl.entry_id = v_entry and jl.debit > 0 and a.subtype = 'Receivable' loop
      perform open_item_raise(p_company, v_entry, l.account_id, 'D', p_source, v_no, coalesce(p_date, current_date), v_due, l.debit);
    end loop;
  end if;
  return true;
end $function$;

-- ── the bills already raised get their due dates ───────────────────────────
update open_items oi set due_date = d.due_date
  from trade_documents d
 where d.company_id = oi.company_id and d.doc_no = oi.doc_no and d.gl_entry = oi.entry_id and d.due_date is not null
   and oi.due_date is null;
update open_items oi
   set due_date = coalesce((select min(i.due_date) from car_installments i where i.contract_id = c.id), c.start_date, c.contract_date)
  from car_contracts c
 where oi.doc_type = 'car_sale' and c.company_id = oi.company_id and c.contract_no = oi.doc_no and oi.due_date is null;
update open_items
   set due_date = (date_trunc('month', doc_date) + interval '1 month - 1 day')::date
 where doc_type = 'car_scharge_month' and due_date is null;
update open_items oi
   set due_date = oi.doc_date + coalesce(nullif(p.credit_days, 0), a.credit_days, 0)
  from accounts a left join parties p on p.id = a.party_id
 where a.id = oi.account_id and oi.due_date is null;

-- ── every entry already void is released ───────────────────────────────────
-- RCT-00001 among them: its 10,000 goes back to CI-000005.
do $$
declare e record;
begin
  for e in select id, entry_no from journal_entries where status = 'void' loop
    perform journal_entry_release_open_items_for(e.id, e.entry_no);
  end loop;
end $$;

-- ── post-conditions ────────────────────────────────────────────────────────
do $chk$
declare v_out numeric; v_n int; v_id uuid; v_ci uuid; v_co uuid;
begin
  select outstanding_base, id, company_id into v_out, v_ci, v_co from open_items where doc_no = 'CI-000005';
  if v_out <> 123000 then raise exception '386: CI-000005 outstanding is %, not 123,000 after the void receipt was released', v_out; end if;
  if exists (select 1 from allocations a join journal_entries e on e.id = a.settle_entry_id where e.status = 'void') then
    raise exception '386: a void entry still holds an allocation';
  end if;
  select count(*) into v_n from open_items where due_date is null;
  if v_n > 0 then raise exception '386: % bills still have no due date', v_n; end if;
  if (select due_date from open_items where doc_no = 'CI-000005') <> date '2026-09-01' then
    raise exception '386: CI-000005 is not due on its first instalment';
  end if;
  if (select due_date from open_items where doc_no = 'MSC-00001') <> date '2026-09-30' then
    raise exception '386: MSC-00001 is not due at the end of its month';
  end if;
  if (select due_date from open_items where doc_no = 'PV-00004') <> date '2026-09-14' then
    raise exception '386: PV-00004 did not take the voucher''s due date';
  end if;

  -- Rehearsal, rolled back: a receipt adjusted against the bill, then voided,
  -- gives the bill back; the bill itself refuses to be voided while the
  -- receipt stands.
  begin
    select id into v_id from journal_entries where entry_no = 'RCT-00002';
    update journal_entries set status = 'posted' where id = v_id;
    insert into allocations(company_id, open_item_id, settle_entry_id, amount_base, note)
    values (v_co, v_ci, v_id, 10000, 'rehearsal');
    update open_items set outstanding_base = outstanding_base - 10000 where id = v_ci;
    begin
      update journal_entries set status = 'void' where entry_no = 'CI-000005';
      raise exception '386 rehearsal: the settled invoice was voided';
    exception when others then
      if sqlerrm not like '%adjusted against by RCT-00002%' then raise; end if;
    end;
    update journal_entries set status = 'void' where id = v_id;
    select outstanding_base into v_out from open_items where id = v_ci;
    if v_out <> 123000 then raise exception '386 rehearsal: bill not given back on void (%)', v_out; end if;
    if exists (select 1 from allocations where settle_entry_id = v_id) then raise exception '386 rehearsal: allocation survived the void'; end if;
    raise exception 'ROLLBACK_REHEARSAL';
  exception when others then
    if sqlerrm <> 'ROLLBACK_REHEARSAL' then raise; end if;
  end;
  if (select outstanding_base from open_items where id = v_ci) <> 123000 or exists (select 1 from allocations) then
    raise exception '386: the rehearsal did not roll back';
  end if;
  raise notice '386 ok';
end $chk$;

commit;
